language: node_js
services:
  - docker
node_js:
  - "stable"
script:
  - make build-agent
after_success:
  - make build
  # login for dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make push

  