language: node_js
services:
  - docker
before_install:
  # login for dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #login to heroku
  -  echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_USERNAME" --password-stdin registry.heroku.com
node_js:
  - "stable"
script:
  - make build-agent
after_success:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - heroku container:login
  - make build
  - make push