language: node_js
services:
  - docker
before_install:
  - docker login --username=_ --password=$(HEROKU_API_KEY) registry.heroku.com
node_js:
  - "stable"
script:
  - make build-agent
# after_success:
#   - make build
#   # login for dockerhub
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - make push
deploy:
  provider: script
  script:
  - make build
  - make push
  